export const ATTRIBUTE_QUESTION_ENDINGS: Record<string, string> = {
  mechanism_uniqueness: '程度較高',
  systemic_coherence: '較強',
  cooperation: '較多',
  worker_placement: '成分較多',
  luck: '較多',
  adaptability: '要求較高',
  long_term_planning: '可規劃得較長遠',
  setup_variability: '幅度較大',
  numeric_calculation: '較多',
  process_calculation: '較多',
  interaction_calculation: '較多',
  thematic_integration: '程度較高',
  score_race: '比重較高',
  end_condition: '比重較高',
  personal_puzzle: '成分較多',
  shared_puzzle: '成分較多',
  shared_environment: '變動較大',
  strategic_abstraction: '程度較高',
  engine_building: '比重較高',
  hidden_information: '較多',
  prior_information: '影響較大',
  logical_deduction: '比重較高',
  intentional_inference: '比重較高',
  waiting_for_actions: '時間較長',
  waiting_for_thinking: '時間較長',
  real_time_reaction: '要求較高',
};

export const attributeQuestionEnding = (attributeKey: string) => ATTRIBUTE_QUESTION_ENDINGS[attributeKey] ?? '程度較高';
