UPDATE games SET display_name = '工廠樂翻天', normalized_name = '工廠樂翻天', english_name = 'Factory Funner', updated_at = 1785514481519 WHERE slug LIKE 'factor-funner%' AND merged_into_game_id IS NULL;
UPDATE games SET display_name = '蒸汽帝國', normalized_name = '蒸汽帝國', english_name = 'Imperial Steam', updated_at = 1785514481519 WHERE slug LIKE 'imperial-steam%' AND merged_into_game_id IS NULL;
UPDATE games SET display_name = '天空植物園', normalized_name = '天空植物園', english_name = 'Planta Nubo', updated_at = 1785514481519 WHERE slug LIKE 'planta-nubo%' AND merged_into_game_id IS NULL;
UPDATE games SET display_name = 'PARKS 國家公園', normalized_name = 'parks國家公園', english_name = 'PARKS', updated_at = 1785514481519 WHERE slug LIKE 'park%' AND merged_into_game_id IS NULL;
UPDATE games SET display_name = 'Race to the Raft', normalized_name = 'racetotheraft', english_name = 'Race to the Raft', updated_at = 1785514481519 WHERE slug LIKE 'race-to-the-raft%' AND merged_into_game_id IS NULL;
UPDATE games SET display_name = 'Voyages', normalized_name = 'voyages', english_name = 'Voyages', updated_at = 1785514481519 WHERE slug LIKE 'voyages%' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Terracotta Army', updated_at = 1785514481519 WHERE display_name = '兵馬俑' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Heaven & Ale', updated_at = 1785514481519 WHERE display_name = '天堂與麥酒' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Mobile Markets: A Smartphone Inc. Game', updated_at = 1785514481519 WHERE display_name = '手機帝國2：商戰' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Isle of Skye: From Chieftain to King', updated_at = 1785514481519 WHERE display_name = '斯凱島' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Terraforming Mars', updated_at = 1785514481519 WHERE display_name = '殖民火星' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Bärenpark', updated_at = 1785514481519 WHERE display_name = '熊熊公園' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Splendor Duel', updated_at = 1785514481519 WHERE display_name = '璀璨寶石：對決' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Kabuto Sumo', updated_at = 1785514481519 WHERE display_name = '甲蟲相撲' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'The Red Cathedral', updated_at = 1785514481519 WHERE display_name = '聖瓦西里大教堂' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Shipyard', updated_at = 1785514481519 WHERE display_name = '船廠' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Ktizo: An Ecosystem Building Cardgame', updated_at = 1785514481519 WHERE display_name = '諾亞星球' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Darwin''s Journey', updated_at = 1785514481519 WHERE display_name = '達爾文之旅' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Hegemony: Lead Your Class to Victory', updated_at = 1785514481519 WHERE display_name = '領國者' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Bus', updated_at = 1785514481519 WHERE display_name = 'Bus' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Carson City', updated_at = 1785514481519 WHERE display_name = 'Carson City' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Cascadero', updated_at = 1785514481519 WHERE display_name = 'Cascadero' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Dokojong', updated_at = 1785514481519 WHERE display_name = 'Dokojong' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Emberleaf', updated_at = 1785514481519 WHERE display_name = 'Emberleaf' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Keyper', updated_at = 1785514481519 WHERE display_name = 'Keyper' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Loot of Lima', updated_at = 1785514481519 WHERE display_name = 'Loot of Lima' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Lovelace & Babbage', updated_at = 1785514481519 WHERE display_name = 'Lovelace & Babbage' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Railroad Ink Challenge', updated_at = 1785514481519 WHERE display_name = 'Railroad Ink Challenge' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Sonora', updated_at = 1785514481519 WHERE display_name = 'Sonora' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Taxi Derby', updated_at = 1785514481519 WHERE display_name = 'Taxi Derby' AND merged_into_game_id IS NULL;
UPDATE games SET english_name = 'Tiletum', updated_at = 1785514481519 WHERE display_name = 'Tiletum' AND merged_into_game_id IS NULL;